name: Java Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Compile and Run Java Files
      run: |
        javac LowerBoundedWildcard.java UpperBoundedWildcard.java
        java LowerBoundedWildcard
        java UpperBoundedWildcard
